<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><!-- HTML generated by Network Solutions Website Builder --><html xmlns="http://www.w3.org/1999/xhtml"><head><link class='webFontsCSSLink' href='http://fonts.googleapis.com/css?family=' rel='stylesheet' type='text/css'><title>Hobo News Home</title><meta name="robots" content="index, follow" /><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1" /><meta http-equiv="cache-control" content="no-cache"/><meta http-equiv="pragma" content="no-cache"/><meta http-equiv="expires" content="-1"/><script type="text/javascript" src="/scripts/user.js"></script><script type="text/javascript" src="/scripts/jquery.js"></script><script type="text/javascript" src="/scripts/simplegallery.js"></script><script type="text/javascript" src="/scripts/photo_album.js"></script><link type="text/css" href="/scripts/PrebuiltBlockStructure.css" media="screen" rel="stylesheet"><link rel="stylesheet" media="screen" href="/scripts/template.css" id="wb-template.css" /><link rel="stylesheet" media="all" href="/scripts/layout1.css" id="wb-layout1.css" /><link rel="stylesheet" media="all" href="/scripts/website.css" id="wb-website.css" /><link rel="stylesheet" media="all" href="/scripts/designer.css" id="wb-designer.css" /><link rel="stylesheet" media="all" href="/scripts/1.css" id="wb-page.css" /><link rel="stylesheet" media="print" href="/scripts/print.css" id="wb-print.css" /><link rel="stylesheet" media="all" href="/scripts/1custom.css" id="wb-custom.css" /><link rel="stylesheet" media="all" href="/scripts/icwebsiteelement.css" id="wb-icwebsiteelement.css" /><link rel="stylesheet" media="all" href="/share/scripts/PrebuiltBlockStructure.css" id="wb-/share/scripts/PrebuiltBlockStructure.css" /></head><body onload="initClientMenu();sizeColumns();"><!-- Start content section --><div id="wb-container-outer">
<div id="wb-container-inner">
<div id="wb-layout">
<div id="wb-layout-inner">
<div id="wb-layout-top-header">
<div id="wb-navigation-subtop-header">
                        
                    </div>
<div id="wb-top-subbasenav"></div>
</div>
<div id="wb-header-nav">
<div id="wb-navigation-top-header">
<div id="wb-navigation-bottom-header">
							 
						</div>
</div>
</div>
<div id="wb-layout-header">
<div id="wb-layout-header-mask" class="wb_region">
         
      
<table id="wb_con__42340" class="wb_con" cellpadding="0" cellspacing="0" width="100%">
<tr>
<td id="wb_col__45678" class="wb_col" width="88%" valign="top" style="">
<table id="dz-tablewb_element_text__1367945871843_81" class="dz-table" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td align="left">
<div id="wb_element_text__1367945871843_81" class="ic-element">
<div><P style="WIDTH: auto" align=center><FONT style="WIDTH: auto" size=7 face="'arial black', impact, sans-serif"><B style="WIDTH: auto"><I style="WIDTH: auto">Hobo News!</I></B></FONT></P></div>
</div>
</td>
</tr>
</table>
</td><td id="wb_col__5673453" class="wb_col" width="10%" valign="top" style="">
               
            </td>
</tr>
</table>
</div>
</div>
<div id="wb-layout-header-base"></div>
<div id="wb-layout-top-2">
<div id="wb-navigation-subtop">
                        <div><a href="home.html" class="tertiary" target="_self"><h3>Home</h3></a></div>
<div><a href="news.html" class="tertiary" target="_self"><h3>News</h3></a></div>
<div><a href="convention.html" class="tertiary" target="_self"><h3>Convention</h3></a><div class="submenu"><div><a href="convention/schedule.html" class="tertiary" target="_self"><h3>Schedule</h3></a></div><div><a href="convention/hobofaq.html" class="tertiary" target="_self"><h3>Hobo FAQ</h3></a></div><div><a href="convention/hobokingsqueens.html" class="tertiary" target="_self"><h3>Hobo Kings & Queens</h3></a></div></div></div>
<div><a href="museum.html" class="tertiary" target="_self"><h3>Museum</h3></a><div class="submenu"><div><a href="museum/symbols.html" class="tertiary" target="_self"><h3>Symbols</h3></a></div></div></div>
<div><a href="foundation.html" class="tertiary" target="_self"><h3>Foundation</h3></a></div>
<div><a href="gatherings.html" class="tertiary" target="_self"><h3>Gatherings</h3></a></div>
<div><a href="westbound.html" class="tertiary" target="_self"><h3>Westbound</h3></a></div>
<div><a href="hobodays.html" class="tertiary" target="_self"><h3>Hobo Days</h3></a><div class="submenu"><div><a href="hobodays/lodging.html" class="tertiary" target="_self"><h3>Lodging</h3></a></div></div></div>
<div><a href="aroundbritt.html" class="tertiary" target="_self"><h3>Around Britt</h3></a><div class="submenu"><div><a href="aroundbritt/queensgarden.html" class="tertiary" target="_self"><h3>Queens' Garden</h3></a></div><div><a href="aroundbritt/vetswall.html" class="tertiary" target="_self"><h3>Vet's Wall</h3></a></div><div><a href="aroundbritt/aquaticcenter.html" class="tertiary" target="_self"><h3>Aquatic Center</h3></a></div><div><a href="aroundbritt/drafthorseshow.html" class="tertiary" target="_self"><h3>Draft Horse Show</h3></a></div><div><a href="aroundbritt/armstronghouse.html" class="tertiary" target="_self"><h3>Armstrong House</h3></a></div></div></div>
<div><a href="videos.html" class="tertiary" target="_self"><h3>Videos</h3></a></div>
<div><a href="hobomusicians.html" class="tertiary" target="_self"><h3>Hobo Musicians</h3></a></div>
<div><a href="whatisahobo.html" class="tertiary" target="_self"><h3>What is a Hobo?</h3></a><div class="submenu"><div><a href="whatisahobo/hobocode.html" class="tertiary" target="_self"><h3>Hobo Code</h3></a></div><div><a href="whatisahobo/unwanted.html" class="tertiary" target="_self"><h3>Unwanted</h3></a></div><div><a href="whatisahobo/touristunion63.html" class="tertiary" target="_self"><h3>Tourist Union 63</h3></a></div></div></div>
<div><a href="contactus.html" class="tertiary" target="_self"><h3>Contact Us</h3></a></div>
<div><a href="links.html" class="tertiary" target="_self"><h3>Links</h3></a></div>
<div><a href="hobomail.html" class="tertiary" target="_blank"><h3>Hobo Mail</h3></a></div>

                    </div>
<div id="wb-top-subbasenav"></div>
</div>
<div id="wb-container-contentwrapper">
<div id="wb-layout-sidebar">
<div id="wb-navigation">
<div id="wb-navigation-top">
<div id="wb-navigation-bottom">
                                    <div><a href="home.html" class="tertiary" target="_self"><h3>Home</h3></a></div>
<div><a href="news.html" class="tertiary" target="_self"><h3>News</h3></a></div>
<div><a href="convention.html" class="tertiary" target="_self"><h3>Convention</h3></a><div class="submenu"><div><a href="convention/schedule.html" class="tertiary" target="_self"><h3>Schedule</h3></a></div><div><a href="convention/hobofaq.html" class="tertiary" target="_self"><h3>Hobo FAQ</h3></a></div><div><a href="convention/hobokingsqueens.html" class="tertiary" target="_self"><h3>Hobo Kings & Queens</h3></a></div></div></div>
<div><a href="museum.html" class="tertiary" target="_self"><h3>Museum</h3></a><div class="submenu"><div><a href="museum/symbols.html" class="tertiary" target="_self"><h3>Symbols</h3></a></div></div></div>
<div><a href="foundation.html" class="tertiary" target="_self"><h3>Foundation</h3></a></div>
<div><a href="gatherings.html" class="tertiary" target="_self"><h3>Gatherings</h3></a></div>
<div><a href="westbound.html" class="tertiary" target="_self"><h3>Westbound</h3></a></div>
<div><a href="hobodays.html" class="tertiary" target="_self"><h3>Hobo Days</h3></a><div class="submenu"><div><a href="hobodays/lodging.html" class="tertiary" target="_self"><h3>Lodging</h3></a></div></div></div>
<div><a href="aroundbritt.html" class="tertiary" target="_self"><h3>Around Britt</h3></a><div class="submenu"><div><a href="aroundbritt/queensgarden.html" class="tertiary" target="_self"><h3>Queens' Garden</h3></a></div><div><a href="aroundbritt/vetswall.html" class="tertiary" target="_self"><h3>Vet's Wall</h3></a></div><div><a href="aroundbritt/aquaticcenter.html" class="tertiary" target="_self"><h3>Aquatic Center</h3></a></div><div><a href="aroundbritt/drafthorseshow.html" class="tertiary" target="_self"><h3>Draft Horse Show</h3></a></div><div><a href="aroundbritt/armstronghouse.html" class="tertiary" target="_self"><h3>Armstrong House</h3></a></div></div></div>
<div><a href="videos.html" class="tertiary" target="_self"><h3>Videos</h3></a></div>
<div><a href="hobomusicians.html" class="tertiary" target="_self"><h3>Hobo Musicians</h3></a></div>
<div><a href="whatisahobo.html" class="tertiary" target="_self"><h3>What is a Hobo?</h3></a><div class="submenu"><div><a href="whatisahobo/hobocode.html" class="tertiary" target="_self"><h3>Hobo Code</h3></a></div><div><a href="whatisahobo/unwanted.html" class="tertiary" target="_self"><h3>Unwanted</h3></a></div><div><a href="whatisahobo/touristunion63.html" class="tertiary" target="_self"><h3>Tourist Union 63</h3></a></div></div></div>
<div><a href="contactus.html" class="tertiary" target="_self"><h3>Contact Us</h3></a></div>
<div><a href="links.html" class="tertiary" target="_self"><h3>Links</h3></a></div>
<div><a href="hobomail.html" class="tertiary" target="_blank"><h3>Hobo Mail</h3></a></div>

                                </div>
</div>
</div>
<div id="wb-basenav"></div>
<div id="wb-navbasewrap" class="wb_region">
<div class="wb_dropzone_y">&nbsp;</div>
         
      
<table id="dz-tablewb_element_guestbook__1368022212953_69" class="dz-table" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td align="center">
<div id="wb_element_guestbook__1368022212953_69" class="ic-element">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
<!--Start of GuestBook code version 1.1 - brought to you by MyComputer.com www.mycomputer.com - Do NOT alter this code!-->
<tr>
<td colspan="2" align="center" valign="middle"><a href="http://guestbook.superstats.com/guest.html?u=vsign_5464848&b=1&partnerid=28264" onClick="popUp(this.href,'guestbook');return false"><img src="images/gb_black_1.jpg" border="0" alt="Sign Guestbook"></a></td>
</tr>
<tr>
<td colspan="2" align="center" valign="middle"><a href="http://guestbook.superstats.com/guest.html?u=vsign_5464848&b=1&show=1&partnerid=28264" onClick="popUp(this.href,'guestbook');return false"><img src="images/gb_black_2.jpg" border="0" alt="View Guestbook"></a></td>
</tr>
<!--End of MyComputer.com's GuestBook code.-->
</table>
</div>
</td>
</tr>
</table>
</div>
</div>
<div id="wb-layout-main">
<div id="wb-layout-main-inner-1">
<div id="wb-layout-main-inner-2" class="wb_region wb-text-content">
			
		
<table id="wb_cl__12346786" cellpadding="0" cellspacing="0" class="" width="100%">
<tr>
<td>
			
<table id="wb_con__1231925678" class="wb_con" cellpadding="0" cellspacing="0" width="100%">
<tr>
<td id="wb_col__332367856" class="wb_col" width="100%" valign="top" style="">
				
<table id="dz-tablewb_element_text__1368019980500_42" class="dz-table" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td align="left">
<div id="wb_element_text__1368019980500_42" class="ic-element">
<div><P style="WIDTH: auto" id=ext-gen1395 align=center><FONT style="WIDTH: auto" color=#0000ff size=7 face="tahoma, 'trebuchet ms', sans-serif"><I style="WIDTH: auto"><B style="WIDTH: auto">Hobo News!</B></I></FONT></P></div>
</div>
</td>
</tr>
</table>
<table id="dz-tablewb_element_pa__1377095372906_5" class="dz-table" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td align="center">
<div id="wb_element_pa__1377095372906_5" class="ic-element">
<!--New Photoalbum-->
<div id="wb_element_pa__1377095372906_5_sub" class="wb_element_pa" style="text-align:center;width:100%;font-size:14px;;font-family:Arial" album_type="2" showTitles="false" bg_color="#ffffff" thumblayout="square" text_color="#000000" text_font="Arial" text_size="14" text_font_family="arial, verdana, sans-serif" autoplay="true" browsing_controls="false" slideshow_delay="6000" relative_file_path="" thumbnails_per_row="3">
<div id="wb_element_pa__1377095372906_5_sub_gallery" style="margin:auto;width:100%; color:#ffffff; background-color:#ffffff;">
				Photo Album Gallery Place Holder - Please wait while the Photo Album loads.
				If the album does not show, please refresh the page to try again.
			</div>
<div id="wb_element_pa__1377095372906_5_sub_thumbs" style="width:100%; margin:auto;display:none;">
<div id="wb_element_pa__1377095372906_5_sub_0_thumbContainer" class="wb_element_paThumbContainer" style="color:#000000; font-size: 9px;width:27%;float:left;text-align:center;background-color:#FFFFFF;">
<div id="wb_element_pa__1377095372906_5_sub_0_thumbBlock" class="wb_element_paThumbBlock" style="width:100%;text-align:center;background-color:;">
<img src="images/247_weg.jpg" style="width:10px;" class="wb_element_paThumb" alt="" title="" thumb_width="247" thumb_height="139" orig_width="774" orig_height="436" source_path="images/774_weg.jpg" caption=""></div>
</div>
<div id="wb_element_pa__1377095372906_5_sub_1_thumbContainer" class="wb_element_paThumbContainer" style="color:#000000; font-size: 9px;width:27%;float:left;text-align:center;background-color:#FFFFFF;">
<div id="wb_element_pa__1377095372906_5_sub_1_thumbBlock" class="wb_element_paThumbBlock" style="width:100%;text-align:center;background-color:;">
<img src="images/248_silos.jpg" style="width:10px;" class="wb_element_paThumb" alt="" title="" thumb_width="248" thumb_height="186" orig_width="774" orig_height="580" source_path="images/774_silos.jpg" caption=""></div>
</div>
<div id="wb_element_pa__1377095372906_5_sub_2_thumbContainer" class="wb_element_paThumbContainer" style="color:#000000; font-size: 9px;width:27%;float:left;text-align:center;background-color:#FFFFFF;">
<div id="wb_element_pa__1377095372906_5_sub_2_thumbBlock" class="wb_element_paThumbBlock" style="width:100%;text-align:center;background-color:;">
<img src="images/248_IMG00352-20110811-1907.jpg" style="width:10px;" class="wb_element_paThumb" alt="" title="" thumb_width="248" thumb_height="186" orig_width="774" orig_height="580" source_path="images/774_IMG00352-20110811-1907.jpg" caption=""></div>
</div>
<div class="wb_element_paThumbRowSpacer" style="clear:both"></div>
<div id="wb_element_pa__1377095372906_5_sub_3_thumbContainer" class="wb_element_paThumbContainer" style="color:#000000; font-size: 9px;width:27%;float:left;text-align:center;background-color:#FFFFFF;">
<div id="wb_element_pa__1377095372906_5_sub_3_thumbBlock" class="wb_element_paThumbBlock" style="width:100%;text-align:center;background-color:;">
<img src="images/248_IMG00367-20110813-1107.jpg" style="width:10px;" class="wb_element_paThumb" alt="" title="" thumb_width="248" thumb_height="186" orig_width="774" orig_height="580" source_path="images/774_IMG00367-20110813-1107.jpg" caption=""></div>
</div>
<div id="wb_element_pa__1377095372906_5_sub_4_thumbContainer" class="wb_element_paThumbContainer" style="color:#000000; font-size: 9px;width:27%;float:left;text-align:center;background-color:#FFFFFF;">
<div id="wb_element_pa__1377095372906_5_sub_4_thumbBlock" class="wb_element_paThumbBlock" style="width:100%;text-align:center;background-color:;">
<img src="images/247_jungle1.jpg" style="width:10px;" class="wb_element_paThumb" alt="" title="" thumb_width="247" thumb_height="139" orig_width="774" orig_height="436" source_path="images/774_jungle1.jpg" caption=""></div>
</div>
<div id="wb_element_pa__1377095372906_5_sub_5_thumbContainer" class="wb_element_paThumbContainer" style="color:#000000; font-size: 9px;width:27%;float:left;text-align:center;background-color:#FFFFFF;">
<div id="wb_element_pa__1377095372906_5_sub_5_thumbBlock" class="wb_element_paThumbBlock" style="width:100%;text-align:center;background-color:;">
<img src="images/139_kinglist.jpg" style="width:10px;" class="wb_element_paThumb" alt="" title="" thumb_width="139" thumb_height="247" orig_width="436" orig_height="774" source_path="images/436_kinglist.jpg" caption=""></div>
</div>
<div class="wb_element_paThumbRowSpacer" style="clear:both"></div>
<div id="wb_element_pa__1377095372906_5_sub_6_thumbContainer" class="wb_element_paThumbContainer" style="color:#000000; font-size: 9px;width:27%;float:left;text-align:center;background-color:#FFFFFF;">
<div id="wb_element_pa__1377095372906_5_sub_6_thumbBlock" class="wb_element_paThumbBlock" style="width:100%;text-align:center;background-color:;">
<img src="images/247_kingqueen2.jpg" style="width:10px;" class="wb_element_paThumb" alt="" title="" thumb_width="247" thumb_height="139" orig_width="774" orig_height="436" source_path="images/774_kingqueen2.jpg" caption=""></div>
</div>
<div id="wb_element_pa__1377095372906_5_sub_7_thumbContainer" class="wb_element_paThumbContainer" style="color:#000000; font-size: 9px;width:27%;float:left;text-align:center;background-color:#FFFFFF;">
<div id="wb_element_pa__1377095372906_5_sub_7_thumbBlock" class="wb_element_paThumbBlock" style="width:100%;text-align:center;background-color:;">
<img src="images/248_IMG00321-20110809-0948.jpg" style="width:10px;" class="wb_element_paThumb" alt="" title="" thumb_width="248" thumb_height="186" orig_width="774" orig_height="580" source_path="images/774_IMG00321-20110809-0948.jpg" caption=""></div>
</div>
<div id="wb_element_pa__1377095372906_5_sub_8_thumbContainer" class="wb_element_paThumbContainer" style="color:#000000; font-size: 9px;width:27%;float:left;text-align:center;background-color:#FFFFFF;">
<div id="wb_element_pa__1377095372906_5_sub_8_thumbBlock" class="wb_element_paThumbBlock" style="width:100%;text-align:center;background-color:;">
<img src="images/247_grave3.jpg" style="width:10px;" class="wb_element_paThumb" alt="" title="" thumb_width="247" thumb_height="139" orig_width="774" orig_height="436" source_path="images/774_grave3.jpg" caption=""></div>
</div>
<div class="wb_element_paThumbRowSpacer" style="clear:both"></div>
<div id="wb_element_pa__1377095372906_5_sub_9_thumbContainer" class="wb_element_paThumbContainer" style="color:#000000; font-size: 9px;width:27%;float:left;text-align:center;background-color:#FFFFFF;">
<div id="wb_element_pa__1377095372906_5_sub_9_thumbBlock" class="wb_element_paThumbBlock" style="width:100%;text-align:center;background-color:;">
<img src="images/193_hobo2.jpg" style="width:10px;" class="wb_element_paThumb" alt="" title="" thumb_width="193" thumb_height="248" orig_width="603" orig_height="774" source_path="images/603_hobo2.jpg" caption=""></div>
</div>
<div id="wb_element_pa__1377095372906_5_sub_10_thumbContainer" class="wb_element_paThumbContainer" style="color:#000000; font-size: 9px;width:27%;float:left;text-align:center;background-color:#FFFFFF;">
<div id="wb_element_pa__1377095372906_5_sub_10_thumbBlock" class="wb_element_paThumbBlock" style="width:100%;text-align:center;background-color:;">
<img src="images/248_francar2.jpg" style="width:10px;" class="wb_element_paThumb" alt="" title="" thumb_width="248" thumb_height="248" orig_width="491" orig_height="491" source_path="images/491_francar2.jpg" caption=""></div>
</div>
<div id="wb_element_pa__1377095372906_5_sub_11_thumbContainer" class="wb_element_paThumbContainer" style="color:#000000; font-size: 9px;width:27%;float:left;text-align:center;background-color:#FFFFFF;">
<div id="wb_element_pa__1377095372906_5_sub_11_thumbBlock" class="wb_element_paThumbBlock" style="width:100%;text-align:center;background-color:;">
<img src="images/248_crowns.jpg" style="width:10px;" class="wb_element_paThumb" alt="" title="" thumb_width="248" thumb_height="186" orig_width="774" orig_height="580" source_path="images/774_crowns.jpg" caption=""></div>
</div>
<div class="wb_element_paThumbRowSpacer" style="clear:both"></div>
<div id="wb_element_pa__1377095372906_5_sub_12_thumbContainer" class="wb_element_paThumbContainer" style="color:#000000; font-size: 9px;width:27%;float:left;text-align:center;background-color:#FFFFFF;">
<div id="wb_element_pa__1377095372906_5_sub_12_thumbBlock" class="wb_element_paThumbBlock" style="width:100%;text-align:center;background-color:;">
<img src="images/247_dtbritt.jpg" style="width:10px;" class="wb_element_paThumb" alt="" title="" thumb_width="247" thumb_height="139" orig_width="774" orig_height="436" source_path="images/774_dtbritt.jpg" caption=""></div>
</div>
<div id="wb_element_pa__1377095372906_5_sub_13_thumbContainer" class="wb_element_paThumbContainer" style="color:#000000; font-size: 9px;width:27%;float:left;text-align:center;background-color:#FFFFFF;">
<div id="wb_element_pa__1377095372906_5_sub_13_thumbBlock" class="wb_element_paThumbBlock" style="width:100%;text-align:center;background-color:;">
<img src="images/247_foodline.jpg" style="width:10px;" class="wb_element_paThumb" alt="" title="" thumb_width="247" thumb_height="139" orig_width="774" orig_height="436" source_path="images/774_foodline.jpg" caption=""></div>
</div>
<div id="wb_element_pa__1377095372906_5_sub_14_thumbContainer" class="wb_element_paThumbContainer" style="color:#000000; font-size: 9px;width:27%;float:left;text-align:center;background-color:#FFFFFF;">
<div id="wb_element_pa__1377095372906_5_sub_14_thumbBlock" class="wb_element_paThumbBlock" style="width:100%;text-align:center;background-color:;">
<img src="images/247_Almanactour.jpg" style="width:10px;" class="wb_element_paThumb" alt="" title="" thumb_width="247" thumb_height="139" orig_width="774" orig_height="436" source_path="images/774_Almanactour.jpg" caption=""></div>
</div>
<div class="wb_element_paThumbRowSpacer" style="clear:both"></div>
</div>
</div>
</div>
</td>
</tr>
</table>
<table id="dz-tablewb_element_text__1376166080001_43" class="dz-table" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td align="left">
<div id="wb_element_text__1376166080001_43" class="ic-element">
<div><FONT style="WIDTH: auto" color=#ff0000 size=5><I style="WIDTH: auto"><B style="WIDTH: auto">New King Frog and Queen Bookworm Bonnie!!!</B></I></FONT></div>
</div>
</td>
</tr>
</table>
<table id="dz-tablewb_element_text__1368020172703_43" class="dz-table" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td align="left">
<div id="wb_element_text__1368020172703_43" class="ic-element">
<div><P style="WIDTH: auto" align=center><B style="WIDTH: auto"><FONT style="WIDTH: auto" color=#ff0000 size=5>The dates for the 2014 National Hobo Convention are August 8, 9, 10 &amp; 11th!</FONT></B></P></div>
</div>
</td>
</tr>
</table>
<table id="dz-tablewb_element_text__1368119568312_76" class="dz-table" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td align="left">
<div id="wb_element_text__1368119568312_76" class="ic-element">
<div><P style="MARGIN: 0px; WIDTH: auto">&nbsp;</P>
<P style="MARGIN: 0px; WIDTH: auto"><B style="WIDTH: auto"><FONT style="WIDTH: auto" color=#ff0000>Museum hours are:&nbsp; June 1- August 15&nbsp; Monday through Friday 10a.m. till 5p.m.</FONT></B></P>
<P style="MARGIN: 0px; WIDTH: auto"><B style="WIDTH: auto"><FONT style="WIDTH: auto" color=#ff0000>or by appointment&nbsp; Bus Tours are welcome&nbsp;&nbsp;&nbsp; $3 admission fee&nbsp;&nbsp; Call 641-843-9104 or email </FONT></B><A style="WIDTH: auto" id=ext-gen1295 href="mailto:lindah@hobo.com" jQuery17106475538987747944="1302" jQuery1356627002734="297"><FONT style="WIDTH: auto" color=#ff0000><B style="WIDTH: auto">lindah@hobo.com</B></FONT></A><B style="WIDTH: auto"><FONT style="WIDTH: auto" color=#ff0000> to make arrangements</FONT></B></P></div>
</div>
</td>
</tr>
</table>
<table id="dz-tablewb_element_counter__1368021781937_64" class="dz-table" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td align="center">
<div id="wb_element_counter__1368021781937_64" class="ic-element">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
<tr>
<td colspan="2" align="center" valign="middle">
<!--Counter code version 1.0.  Do NOT alter this code! http://counter.mycomputer.com--><img alt="Counter" src="http://counter.superstats.com/c.count?u=vsign_5464848&c=1" border="0"><!--End of Counter Code--></td>
</tr>
</table>
</div>
</td>
</tr>
</table>
</td>
</tr>
</table>
		
</td>
</tr>
</table>
</div>
</div>
</div>
<div style="clear: both"></div>
</div>
<div id="wb-layout-footer">
<div id="wb-layout-footer-inner-1" class="wb_region">
<div class="wb_dropzone_y">&nbsp;</div>
         
      
</div>
</div>
</div>
</div>
</div>
</div><table border="0" width="100%" cellpadding="0" cellspacing="0" id="other_footer">
<tr>
<td align="left" valign="middle"><p style="font-size: 10px; font-style: normal; font-family: arial,verdana,sans-serif;  font-style: normal;"><a style="text-decoration: none; font-size: 10px; font-style: normal; font-family: arial,verdana,sans-serif;  font-style: normal;" title="Website" href="http://ads.networksolutions.com/landing?code=P111C100S1N0B142A1D401E0000V100" >Website</a> powered by Network Solutions&reg;</p></td>
</tr>
</table>
<!-- End content section --><!-- Start nsWebstats code.  Copyright 2010 networksolutions.com More info available at http://networksolutions.com --><script type="text/javascript">var pageName="Home"; document.write(unescape('%3Cscript src="'+(location.href.split(':')[0] =='https'?'https':'http')+'://stats.netsolads.com/jsconfig?pid=284046904%26mg=all%26lc=1%26pe=1"%3E%3C/script%3E'));</script><!--End nsWebStats tracking code. --></body></html>